### ISSUE TITLE
No way to give Kasasa the screenshot permission in GNOME settings

### ISSUE THREAD

**Issue by sylvesterroos** [KelvinNovais/Kasasa#14]
When I try to take a screenshot with Kasasa I get the following error:
```
Screenshot failed

Ensure Screenshot permission is enabled in Settings -> Apps -> Kasasa
```

The problem is that GNOME does not allow me to set this permission:
![image](https://github.com/user-attachments/assets/4861f206-5bb0-4fcc-9e34-68e29302b6e7)

**Comment by KelvinNovais** [comment]
In fact, Kasasa isn't asking for this permission at the first time, so this option won't appear on the settings.

Even if the lack of the permission formality, Kasasa should be able to take a screenshot. So let's go one step back, does the screenshot fails every time?

**Comment by sylvesterroos** [comment]
Taking the screenshot itself seems to work every time; I see the new screenshot in `~/Pictures/Screenshots/`.

Sometimes Kasasa opens this screenshot in its own window. Other times it fails with the error message.

Sometimes taking a new screenshot with the 'Retake screenshot' button correctly displays the new screenshot. When it fails, sometimes it simply keeps displaying the old screenshot, and sometimes it shows the error message.

Whether it works or not seems to very much change between logins.

All in all, it's very tricky to give you something you can work with. Are there any error logs that I can send your way?

**Comment by KelvinNovais** [comment]
Let's divide this issue into 2:

1) Permission
The permission is not requeried for interactive screenshots, just for the full screen ones (when there isn't user interaction).
The dialog was removed on commit 0dfc57e73b927e33470860404d2fc3b63e846c82, so I'm going to close this issue soon.

2) Screenshot failing
I've already noticed this problem, and it varies between logins, as you said; it usually happens when taking bigger screenshots.
It's more likely to be the Portal API, since I face the same problem with other apps that consume it.
Please refer to the issue #19
