### ISSUE TITLE
[Feature request] Auto discard

### ISSUE THREAD

**Issue by AxelSkye** [KelvinNovais/Kasasa#5]
Hi! Love the concept, thank you for your work.

I would be possible if it could be enabled to autoclose the window after a certain time (like macos screenshot thumbnail)

Again, thank you!

**Comment by KelvinNovais** [comment]
The Kasasa's purpose is to grab some information (like a formula, a matrix, etc.) and make it always visible, so it prevents you from switching between windows or workspaces. It's useful when you're taking handwriting notes, for example.
In this situation, auto discarding would defeat the original purpose.

It's not intented to work as thumbnailer, exactly as MacOS does. However, I don't discard adding similar features only if the workflow don't get broken/messy.

Such implementation could be better done by GNOME itself, since they have full control over the DE. Kasasa would face some problems:
1. It's not possible to auto pin the window, a user interaction is needed - it could get covered by other windows;
2. It's not possible to set the position of the window, so Kasasa won't appear on the screen corner.

**Comment by KelvinNovais** [comment]
I'll let this issue open, so people can make suggestions. I'm also going to see what's possible to do.

**Comment by KelvinNovais** [comment]
Hey there! A simple auto discarding may be very useful.

This feature was added on commit a350ecb7a9dababf4cfc37da9013f06fe64bed65, and will be released soon.

Currently the user can toggle this function on the settings, but I think I'll add a button on the vertical, so the user can trigger it once in a while.

However, I still don't know if you would like just enabling a simple auto discarding, or make the app act like a thumbnail... let me know that.

**Comment by SimonAulet** [comment]
Hi! In my case, autodiscarding with option to save (like option to copy, that already exists) or option to quickly erase screenshot would be perfect.
In my specific workflow, I take a screenshot of a formula or some description, open it and make it always visible for short ussage time, then erase it. So your application fits perfectly to my needs. Thaks a lot for its development!
